#+TITLE: ... GNU Make
#+OPTIONS: toc:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: author:nil
#+OPTIONS: date:nil

* List of build systems
* Features offered
* The Article
Update: The original intent in this article was just to make a
post. But the words exceeded the limit. And hence I posted it as an
article. As @Sasi points it out, the subject requires elaboration. So
here is my attempt to write a more complete article.
* Art of Orchestration - GNU Make
