#+TITLE: Perception of Right and Wrong
#+DATE: 2007-08-17
#+OPTIONS: toc:nil

Many times we have all seen someone doing something wrong. And we simply do not understand why that person is doing it that way. Even if you talk to him about his wrongdoings, he will not accept it. He thinks he is doing right.

Our company bus driver drives very rashly. For him, there is no meaning of speed limits indicated on boards by the roadside. And he is always in a hurry. He cannot wait for people to give him way on the road. I do not remember the bus horn being silent for more than 20 seconds in moderate traffic conditions. He keeps pressing it without considering that the person driving in front of him is also in a hurry and also has to reach somewhere as soon as possible. Our driver thinks that only he has to reach the office and no one else.

One day after reaching the office, when I was getting down, I asked the driver, "Kyon itna horn bajate ho bhai" (brother, why do you use so much horn). He smiled and innocently said, "Sir horn nahin bajaenge to koi side nahin dega" (Sir, if I don't blow the horn then no one will give us way). And the next day he was driving the same way again, no difference.

If we look at it closely, we will find that nothing is wrong with the driver. It is only the way he perceives things as right and wrong. He grew up in such surroundings where he was not told about what is right and what is wrong. So he sees things slightly differently. Similar to the driver's case, another example would be the terrorists who are spread all over the world. They kill people and do not regret it either. They see this as right because no one has taught them that it is wrong. In terrorist camps, young people are trained by changing their perception of right and wrong. They are brainwashed so that they do not feel sorry while killing someone.

Similar is the case when we are sitting in a meeting room, discussing a design. Sometimes, despite having a better design in front of us, we tend to stick to what we have proposed. And we try to prove the superiority of our proposed design over the better one. Here, ego is a more powerful element than perception.

We have millions of cells in our brain, working together to enable our body to judge right and wrong in various circumstances. Keeping our mind surrounded with nice and right thoughts could make our minds better decision-making devices.
