#+TITLE: Scalable Teams

1. Everyone in team should make their work count. They are working on
   something really important. That should be the feeling among
   everyone. And this will deliver greater result. On the contrary, if
   only a few in the team think that their work is more important than
   the rest of the team it creates islands in teams. Others will start
   feeling that they are unimportant and eventually the team
   performance suffers.
2. Developing a culture of empathy is important. Empathy is not only
   be for the end users but it is for the team as well. Also, empathy
   should reflect in actions rather than in words.
3. How many times you volunteer for tasks that are important to the
   whole team. And when you do volunteer, check how much side work it
   creates so that ultimately the other members of the team actually
   contribute more the same task.
4. Do you wash utensils or put them into dish-washer for the whole
   team? How often do you do that?
5. Scrum meeting should be joined by everyone who has tasks assigned,
   otherwise other members of the team will feel that a few members
   are priviledged.
6. 
