#+TITLE: The Grand Weight Loss Party
#+DATE: 2007-08-22
#+OPTIONS: toc:nil

About a month ago, we all (Abhilash, Dinesh, and I) started going to the company gymnasium with different motives. Despite having good looks, Abhilash had a misunderstanding that he did not look good. And to rectify that, he started a regular workout every day. I wanted to build some muscle now. I know it is late. But it is never too late, you know. Dinesh has a deep back and wanted to fill that with muscles.

Many things happen on our way to wisdom. Dinesh separated from us as he joined Sequence Design. But Abhilash's achievement was surprising. He lost 10 kg in a month. Check his full advice at [[http://kahani-zindagi-ki.blogspot.com/2007/08/blog-post_7519.html][Abhilash's Blog]]. And we needed no more reasons to celebrate. We started asking for a party when he lost 9.5 kg. He promised to throw a party when he completed a 10 kg loss. We said ok.

Although Abhilash tried hard to keep his weight loss below 10 kg, yesterday he was 11.5 kg less than where he started. We reminded him of his promise. Ripul insisted on a dinner party. But we could not decide. After some time, Abhilash leaked the secret of Dal-Bati. And Ripul again insisted on a dinner party with Dal-Bati in the course. Abhilash agreed.

All of us left the office at 5:00 PM. Abhilash went home to help Uma prepare a nice treat for all of us, and we (Ripul and I) headed towards my home to pick up Sarita and Naini. Then we picked up Preeti from her office and reached Kendriya Vihar, Sector 50, Noida, at Abhilash's residence for a mouth-watering supper. Rahul was busy in some teleconference so he could not attend the party.

All had more than twice our usual capacity. The meal was so tasty that we could not resist taking more and more and more... seriously. Now I know the secret behind Abhilash's weight gain. Abhilash resisted too much but could not help it. He also ate twice his usual diet. Then we had sweets too. Overall, a very well-hosted treat.

Thanks Abhilash and Uma for the best hospitality. But Abhilash, now you should start eating a full diet, leaving your specialised low-calorie meal. Now you look super cool.
